### ISSUE TITLE
TypeError prevents object creation.

### ISSUE THREAD

**Issue by SirTangent** [Frexeptabel/notion-api#5]
I used the following code to run the library (of course, I used an actual token):
```
const Notion = require("notion-api-js");

let api = new Notion({
    token: "<some token>"
});
```

I end up getting a TypeError upon running:
```
TypeError: Notion is not a constructor
```

**Comment by cstrnt** [comment]
Hi there,

thanks for clarifying! You need to import it like that using the require syntax: 
```js
const Notion = require("notion-api-js").default;

// following code
```

I will edit the readme so others won't have the same issue! Thank you 😄

**Comment by SirTangent** [comment]
Hi Tim,

adding the ```.default``` at the end really helped. The wrapper works for me now. Thank you for clarifying this.
